#!/usr/bin/env python
"""Emit every number the prose quotes as a LaTeX macro, computed from results/.

The submitted version quoted means, win counts and speedups that disagreed with
its own tables (e.g. "3--10x faster on average" is false for NCF vs InvGrad;
"wins on 9 of 10 datasets in both LightGCN and NCF" is 8 of 10 for LightGCN).
That happens when prose is written by hand against tables that are later
regenerated. Here the prose \input{}s this file, so the two cannot drift.

Usage:  python scripts/build_macros.py --runs results/main --out paper/macros.tex
"""
from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

import numpy as np

DATASETS = ["lastfm", "ml", "delicious", "douban-book", "amazon-beauty",
            "amazon-book", "amazon-kindle", "gowalla", "iFashion", "yelp2018"]
MODELS = ["mf", "lightgcn", "ncf"]
BASELINES = ["invert_grad", "lti", "raifle"]


def load(dirs):
    runs = {}
    for d in dirs:
        for f in sorted(Path(d).glob("*.json")):
            if f.name.startswith("_"):
                continue
            try:
                r = json.loads(f.read_text())
            except Exception:
                continue
            runs[(r["dataset"], r["model"], r.get("attack", "paired_probe"))] = r
    return runs


def total_time(r):
    t = r.get("timing", {})
    return float(t.get("prepare_sec", 0)) + float(t.get("solve_sec", 0))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", nargs="+", default=["results/main"])
    ap.add_argument("--out", default="paper/macros.tex")
    a = ap.parse_args()
    R = load(a.runs)
    L = ["% AUTO-GENERATED by scripts/build_macros.py -- do not edit.",
         "% Every number the prose quotes lives here so prose and tables cannot drift.",
         ""]

    def macro(name, val, fmt="{:.4f}"):
        L.append(f"\\newcommand{{\\{name}}}{{{fmt.format(val) if isinstance(val,float) else val}}}")

    cov = 0
    for m in MODELS:
        cs = [R[(d, m, "paired_probe")]["cos"]["cos_mean"]
              for d in DATASETS if (d, m, "paired_probe") in R]
        if not cs:
            continue
        cov += len(cs)
        nm = m.replace("-", "")
        macro(f"trip{nm}Mean", float(np.mean(cs)))
        macro(f"trip{nm}Min", float(np.min(cs)))
        macro(f"trip{nm}Max", float(np.max(cs)))
        macro(f"trip{nm}N", str(len(cs)))
        # null floor
        fl = [R[(d, m, "paired_probe")]["cos"].get("cos_trivial_floor")
              for d in DATASETS if (d, m, "paired_probe") in R]
        fl = [x for x in fl if x is not None]
        if fl:
            macro(f"null{nm}Min", float(np.min(fl)))
            macro(f"null{nm}Max", float(np.max(fl)))
        # wins vs each baseline, and cells that fail to clear their own null
        for b in BASELINES:
            w = sum(1 for d in DATASETS
                    if (d, m, "paired_probe") in R and (d, m, b) in R
                    and R[(d, m, "paired_probe")]["cos"]["cos_mean"] > R[(d, m, b)]["cos"]["cos_mean"])
            n = sum(1 for d in DATASETS if (d, m, "paired_probe") in R and (d, m, b) in R)
            macro(f"win{nm}{b.replace('_','')}", f"{w} of {n}")
        nfail = sum(1 for d in DATASETS
                    if (d, m, "paired_probe") in R
                    and R[(d, m, "paired_probe")]["cos"].get("cos_trivial_floor") is not None
                    and R[(d, m, "paired_probe")]["cos"]["cos_mean"]
                        <= R[(d, m, "paired_probe")]["cos"]["cos_trivial_floor"])
        macro(f"belowNull{nm}", str(nfail))
        # speedups
        for b in BASELINES:
            rs = [(total_time(R[(d, m, b)]), total_time(R[(d, m, "paired_probe")]))
                  for d in DATASETS if (d, m, b) in R and (d, m, "paired_probe") in R]
            rs = [(x, y) for x, y in rs if y > 0]
            if not rs:
                continue
            sp = [x / y for x, y in rs]
            macro(f"speed{nm}{b.replace('_','')}Mean", float(np.mean(sp)), "{:.1f}")
            macro(f"speed{nm}{b.replace('_','')}Max", float(np.max(sp)), "{:.1f}")
            macro(f"speed{nm}{b.replace('_','')}Min", float(np.min(sp)), "{:.1f}")
    macro("cellsCovered", str(cov))
    Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    Path(a.out).write_text("\n".join(L) + "\n")
    print(f"wrote {a.out}  ({len(L)-3} macros, {cov} (dataset,model) cells)")


if __name__ == "__main__":
    main()
